# Generated by Django 4.0.2 on 2022-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiotix', '0002_alter_language_language_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_type',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Telegu', 'Telegu'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Punjabi', 'Punjabi'), ('Gujarati', 'Gujarati')], max_length=50, unique=True),
        ),
    ]
