# Generated by Django 4.0.2 on 2022-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiotix', '0003_alter_genre_type_alter_language_language_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(upload_to='webserieepi/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movieimg/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='webserie',
            name='image',
            field=models.ImageField(upload_to='webserieimg/'),
        ),
    ]
