# Generated by Django 4.0.2 on 2022-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiotix', '0004_alter_episode_video_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webserie',
            name='cast',
            field=models.ManyToManyField(to='codiotix.Cast'),
        ),
    ]
