# Generated by Django 4.0.2 on 2022-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiotix', '0005_webserie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default=0, upload_to='genreimg/'),
        ),
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(default=0, upload_to='languageimg/'),
        ),
    ]
